name: Build images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TAG_NAME: 3.2.2-alpine
  USER_NAME: krmbzds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push BUILDER image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:Builder'
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ env.USER_NAME }}/rails-dev-builder:${{ env.TAG_NAME }}
            ${{ env.USER_NAME }}/rails-dev-builder:${{ env.TAG_NAME }}
            ghcr.io/${{ env.USER_NAME }}/rails-dev-builder:latest
            ${{ env.USER_NAME }}/rails-dev-builder:latest

      - name: Build and push FINAL image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:Final'
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ env.USER_NAME }}/rails-dev-final:${{ env.TAG_NAME }}
            ${{ env.USER_NAME }}/rails-dev-final:${{ env.TAG_NAME }}
            ghcr.io/${{ env.USER_NAME }}/rails-dev-final:latest
            ${{ env.USER_NAME }}/rails-dev-final:latest
